import axios  from "axios";
import { Buffer } from 'buffer';
import { CodeCard } from "./codeCard";

/**
 * 
 * @param url GitHub-related url, generated by VSCode Extension side.
 * @param useGithubRendered option to choose whether to get rendered HTML directly from GitHub
 * @returns 
 */
export async function reqCodeDataFromGitHubAPI(url: string, useGithubRendered: boolean){
    // Typically, An Endpoint-generated GitHub-related URL be like `https://github.com/OfficeDev/TeamsFx-Samples/blob/master/test.py#L1-L6&xxx`
    if (url.includes("&")){
        const tempList = url.split("&");
        url = tempList[0];
    }
    if (!url.includes("#")){
        return undefined;
    }
    
    // Now the URL will be like `https://github.com/OfficeDev/TeamsFx-Samples/blob/master/test.py#L1-L6`
    const segmentListSharp = url.split("#");
    // `lines` be like `L1-L6`
    const lines = segmentListSharp[1];
    const lineNumList = lines.replace(/L/g,"").split("-");
    // Get startLine and endLine, since we need offset in the list, so -1 is needed.
    const startLine = Number(lineNumList[0]) -1;
    const endLine = Number(lineNumList[1]) -1;
    // `segmentListSharp[0]` be like `https://github.com/OfficeDev/TeamsFx-Samples/blob/master/test.py
    const segmentList = segmentListSharp[0].replace("https://github.com/","").replace("blob/","").split("/");
    // user name is the first element of the segmentList.
    const namespace = segmentList.shift();
    // repo name is the second element of the segmentList.
    const repoName = segmentList.shift();
    // branch name is the third part of the segmentList.
    const branch = segmentList.shift();
    // connect the remaining part to get file path.
    const path = segmentList.reduce((a,b) => a + "/" + b);
   
    var content: string;
    // Use third-part API/lib to render code to HTML.
    if (!useGithubRendered){
        // Request whole content from GitHub API with metadata.
        const rawContent = await reqInfoFromGitHubAPI(namespace, repoName, path, branch);
        // Get certain lines of code.
        const contentToRender = segmentContent(rawContent, startLine, endLine);
        // Get language type from file path, only supports Python and Markdown in the demo.
        const language = getLanguage(path);
        // Render content to HTML by its language type.
        content = await renderContent(language,contentToRender);
    }
    // Directly use GitHub-rendered HTML of the file.
    // Notice: No syntax-highlighting; Hard to get certain lines of code from rendered HTML.
    else {
        content = await reqRenderedHTMLFromGitHub(namespace, repoName, path);
    }

    var card = new CodeCard(`[${branch}]${namespace}/${repoName}/${path}: Lines ${startLine+1} - ${endLine+1}`, content, "github", url);
    return card;
}

/**
 * Function to request file data from GitHub API.
 * @param namespace namespace
 * @param repoName name of the repository
 * @param path path of the file
 * @param branch name of the branch
 * @returns raw content string of the file
 */
 async function reqInfoFromGitHubAPI(namespace: string, repoName: string, path: string, branch: string){
    const GithubToken = getGitHubToken();
    if (branch == undefined){
        branch = 'main'
    }
    const reqURL = `https://api.github.com/repos/${namespace}/${repoName}/contents/${path}`;
    var content:string;
    await axios({
        baseURL: reqURL,
        method: 'get',
        headers: {
            'Accept':'application/vnd.github+json',
            'Authorization':GithubToken
        },
        params:{
            'ref': branch
        }
    }).then( (response) => {
        // Need to decode with base64
        content = Buffer.from(response.data["content"],'base64').toString('utf-8');    
    });
    return content;
}

/**
 * Function to get certain lines of a file content.
 * @param content 
 * @param startLine the index of the starting line
 * @param endLine the index of the ending line
 * @returns content string of certain lines of a file content
 */
 function segmentContent(content:string, startLine:number, endLine: number){
    var retLines:string[] = [];
    var segmentLines = content.split("\n");
    for (let i = startLine; i <= endLine; i++ ){
        retLines.push(segmentLines[i]);
    }
    // Reduce them to a string connected with `\n`.
    return retLines.reduce((a,b)=>a+"\n"+b);
}

/**
 * Naive function to get language type from file suffix.
 * Only supports markdown and python now.
 * @param path path of the file
 * @returns language type of the file
 */
function getLanguage(path:string){
    if (path.includes(".md")){
        return 'md';
    }
    else {
        return 'py'
    }
}

/**
 * Function to render content with its language type.
 * @param language language type of the content.
 * @param contentToRender content to be rendered.
 * @returns HTML string of the content.
 */
async function renderContent(language:string, contentToRender:string){
    // For MarkDown, GitHub provided API to render. 
    // Render with lib and GitHub API are both implemented.
    if (language === 'md'){
        //return renderWithLib(contentToRender);
        return renderWithGithubMdAPI(contentToRender);
    }
    // Python rendering.
    else{
        return renderCodeWithAPI(contentToRender);
    }
}

/**
 * Function to render MarkDown content to HTML with a third-party lib.
 * @param contentToRender MarkDown string to be rendered.
 * @returns HTML string of the content.
 */
function renderWithLib(contentToRender:string){
    var md = require("markdown-it")();
    return md.render(contentToRender);
}

/**
 * Function to render MarkDown content to HTML with GitHub API.
 * @param contentToRender MarkDown string to be rendered.
 * @returns HTML string of the content.
 */
async function renderWithGithubMdAPI(contentToRender:string){
    const GithubToken = getGitHubToken();
    var html = await axios({
        baseURL: "https://api.github.com/markdown",
        method: 'post',
        headers: {
            'Accept':'application/vnd.github+json',
            'Authorization': GithubToken
        },
        data:{
            'text': contentToRender
        }
    }).then( (response) => {       
        return response.data; 
    });
    return html;
}

/**
 * Function to render code with API.
 * This function only renders Python code content.
 * @param contentToRender content to be rendered.
 * @returns HTML string of the content.
 */
 async function renderCodeWithAPI(contentToRender:string){
    console.log(contentToRender)
    var content = await axios({
        baseURL: "http://hilite.me/api",
        method: 'get',
        params:{
            "code":contentToRender
        }
    }).then( (response) => {
        return response.data;     
    });
    console.log(content);
    return content;
}

/**
 * Function to request rendered HTML of GitHub content.
 * @param namespace namespace
 * @param repoName name of the repository
 * @param path path of the file
 * @returns HTML string of the content
 */
 async function reqRenderedHTMLFromGitHub(namespace: string, repoName: string, path: string){
    const GitHubToken = getGitHubToken();
    const reqURL = `https://api.github.com/repos/${namespace}/${repoName}/contents/${path}`;
    var content = await axios({
        baseURL: reqURL,
        method: 'get',
        // The value of the field `Accept` is required to be set to `application/vnd.github.VERSION.html` to get GitHub-rendered HTML.
        headers: {
            'Accept':'application/vnd.github.VERSION.html',
            'Authorization': GitHubToken
        },
    }).then( (response) => {
        return response.data;
    });
    return content;
}

/**
 * Function to get GitHub Token from process.env
 * Set in `.env.teamsfx.local`
 * @returns github token for authorization.
 */
function getGitHubToken(){
    const GitHubToken = `token ${process.env.GITHUB_TOKEN}`;
    return GitHubToken;
}